webtalk_init -webtalk_dir D:/fpga/AM_Decoder/AM_Decoder.sim/sim_1/behav/xsim/xsim.dir/ASK_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jun 18 19:41:16 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1b86defe-5b04-4f09-82f7-64ba812ef36a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "760e5599377e4fa0921a600a2567790b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "44" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) Ultra 9 285H" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3686 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "62446496153 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "15" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "859.66_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "21676_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2516282366 -regid "" -xml D:/fpga/AM_Decoder/AM_Decoder.sim/sim_1/behav/xsim/xsim.dir/ASK_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/fpga/AM_Decoder/AM_Decoder.sim/sim_1/behav/xsim/xsim.dir/ASK_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/fpga/AM_Decoder/AM_Decoder.sim/sim_1/behav/xsim/xsim.dir/ASK_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
