# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0.xci
# IP: The module: 'system_AM_decoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# XDC: d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0.xci
# IP: The module: 'system_AM_decoder_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/cordic_0/cordic_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cordic_0 || ORIG_REF_NAME==cordic_0} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_1 || ORIG_REF_NAME==mult_gen_1} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# IP: D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dds_compiler_0 || ORIG_REF_NAME==dds_compiler_0} -quiet] -quiet

# XDC: d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fir_compiler_0 || ORIG_REF_NAME==fir_compiler_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
