# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_param project.vivado.isBlockSynthRun true
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/fpga/AM_Decoder/AM_Decoder.cache/wt [current_project]
set_property parent.project_path D:/fpga/AM_Decoder/AM_Decoder.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/fpga/AM_Decoder/AM_Decoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/FIR_Sample3.25m_Stop60k
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/IQ_FreMix.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/detect.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/phase_creater.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/AM_decoder.v
}
read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/cordic_0/cordic_0.xci

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_0/fir_compiler_0.xci
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_0/constraints/fir_compiler_v7_2.xdc]

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/dds_compiler_0/dds_compiler_0.xci

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1 -new_name system_AM_decoder_0_0 -ip [get_ips system_AM_decoder_0_0]]

if { $cached_ip eq {} } {
close [open __synthesis_is_running__ w]

synth_design -top system_AM_decoder_0_0 -part xc7z020clg484-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
# disable binary constraint mode for IPCache checkpoints
set_param constraints.enableBinaryConstraints false

catch {
 write_checkpoint -force -noxdef -rename_prefix system_AM_decoder_0_0_ system_AM_decoder_0_0.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_AM_decoder_0_0_stub.v
 lappend ipCachedFiles system_AM_decoder_0_0_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_AM_decoder_0_0_stub.vhdl
 lappend ipCachedFiles system_AM_decoder_0_0_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_AM_decoder_0_0_sim_netlist.v
 lappend ipCachedFiles system_AM_decoder_0_0_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ system_AM_decoder_0_0_sim_netlist.vhdl
 lappend ipCachedFiles system_AM_decoder_0_0_sim_netlist.vhdl
set TIME_taken [expr [clock seconds] - $TIME_start]

 config_ip_cache -add -dcp system_AM_decoder_0_0.dcp -move_files $ipCachedFiles -use_project_ipc  -synth_runtime $TIME_taken  -ip [get_ips system_AM_decoder_0_0]
}

rename_ref -prefix_all system_AM_decoder_0_0_

# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_AM_decoder_0_0.dcp
create_report "system_AM_decoder_0_0_synth_1_synth_report_utilization_0" "report_utilization -file system_AM_decoder_0_0_utilization_synth.rpt -pb system_AM_decoder_0_0_utilization_synth.pb"

if { [catch {
  file copy -force D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1/system_AM_decoder_0_0.dcp D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1/system_AM_decoder_0_0.dcp D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1/system_AM_decoder_0_0_stub.v D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1/system_AM_decoder_0_0_stub.vhdl D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1/system_AM_decoder_0_0_sim_netlist.v D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force D:/fpga/AM_Decoder/AM_Decoder.runs/system_AM_decoder_0_0_synth_1/system_AM_decoder_0_0_sim_netlist.vhdl D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir D:/fpga/AM_Decoder/AM_Decoder.ip_user_files/ip/system_AM_decoder_0_0]} {
  catch { 
    file copy -force D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_stub.v D:/fpga/AM_Decoder/AM_Decoder.ip_user_files/ip/system_AM_decoder_0_0
  }
}

if {[file isdir D:/fpga/AM_Decoder/AM_Decoder.ip_user_files/ip/system_AM_decoder_0_0]} {
  catch { 
    file copy -force D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_AM_decoder_0_0/system_AM_decoder_0_0_stub.vhdl D:/fpga/AM_Decoder/AM_Decoder.ip_user_files/ip/system_AM_decoder_0_0
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
