#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.3 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Jun 15 21:42:43 +0800 2026
# SW Build 2405991 on Thu Dec  6 23:38:27 MST 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xil_defaultlib xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_4 processing_system7_vip_v1_0_6 xbip_utils_v3_0_9 xbip_pipe_v3_0_5 xbip_bram18k_v3_0_5 mult_gen_v12_0_14 axi_utils_v2_0_5 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_5 xbip_dsp48_multadd_v3_0_5 dds_compiler_v6_0_17 xlconstant_v1_1_5 fir_compiler_v7_2_11 c_reg_fd_v12_0_5 xbip_addsub_v3_0_5 c_addsub_v12_0_12 cordic_v6_0_14)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2018.3 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/xlinx/Vivado/2018.3/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "D:/xlinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/xlinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/xlinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_4 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/98af/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_processing_system7_0_0/sim/system_processing_system7_0_0.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_ila_0_0/sim/system_ila_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_9 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/0da8/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/442e/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c08f/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/6bb5/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mult_gen_0_0/sim/system_mult_gen_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_mult_gen_0_1/sim/system_mult_gen_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec8e/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/a04b/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/b226/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work dds_compiler_v6_0_17 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/018d/hdl/dds_compiler_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_dds_compiler_0_0/sim/system_dds_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_dds_compiler_0_2/sim/system_dds_compiler_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/4649/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_0/sim/system_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_1/sim/system_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_Valid_logic_0_0/sim/system_Valid_logic_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_Valid_logic_0_1/sim/system_Valid_logic_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fir_compiler_v7_2_11 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/3697/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_fir_compiler_0_0/sim/system_fir_compiler_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_fir_compiler_0_2/sim/system_fir_compiler_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_2/sim/system_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/system/ip/system_Valid_logic_1_0/sim/system_Valid_logic_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_Valid_logic_1_1/sim/system_Valid_logic_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_mult_gen_2_0/sim/system_mult_gen_2_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_mult_gen_2_1/sim/system_mult_gen_2_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/cbdd/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_5 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/87fb/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_12 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/6b5f/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cordic_v6_0_14 $vhdlan_opts \
    "$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7bb6/hdl/cordic_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_cordic_0_0/sim/system_cordic_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_c_addsub_0_0/sim/system_c_addsub_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/70cf/hdl" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/85a3" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/7d3c/hdl/verilog" +incdir+"$ref_dir/../../../../AM_Decoder.srcs/sources_1/bd/system/ipshared/c45e/hdl/verilog" +incdir+"D:/xlinx/Vivado/2018.3/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_2_0/sim/system_xlconstant_2_0.v" \
    "$ref_dir/../../../bd/system/ip/system_Valid_logic_3_0/sim/system_Valid_logic_3_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
