#ifndef PFC_INV_USER_CONFIG_H
#define PFC_INV_USER_CONFIG_H

/*
 * 联合工程唯一的人工配置入口。
 *
 * 数据流边界：本文件只保存编译期参数和标定结果，不访问HAL、不启动外设。
 * pfc_user_config.h与inv_user_config.h只是兼容包装，日常调试只修改本文件。
 * 默认配置采用已经分别完成独立验证的36 V赛题档：PD0短按后PFC尝试投入双闭环，
 * INV同时按独立60 V开环逻辑启动。INV线电压标定只影响显示，不参与开环PWM许可。
 * 需要重新标定ADC时，必须先把STAGE改为RAW_ADC并把PWM_ENABLE改为0U。
 */

#include <stdint.h>

/* ======================== 联合阶段：只选择一个 ======================== */
#define PFC_INV_STAGE_RAW_ADC          (0U) /* 只看原始码，所有PWM禁止。 */
#define PFC_INV_STAGE_PFC_ONLY         (1U) /* PFC闭环，INV保持关闭。 */
#define PFC_INV_STAGE_INV_ONLY         (2U) /* INV开环，线电压ADC只用于观察。 */
#define PFC_INV_STAGE_JOINT_LOW_POWER  (3U) /* PFC可选运行，INV不等待母线闭环。 */
#define PFC_INV_STAGE_JOINT_CONTEST    (4U) /* 36 V联合档，INV优先保持开环发波。 */

#define PFC_INV_PROFILE_5V             (0U)
#define PFC_INV_PROFILE_36V            (1U)

/*
 * 用户通常只修改阶段、参数档和PWM总许可。PFC标定确认按5 V/36 V参数档分别保存，
 * 切换参数档时不会继承另一档的确认状态；INV仍使用独立确认位。
 */
#define PFC_INV_STAGE                  PFC_INV_STAGE_JOINT_CONTEST
#define PFC_INV_ACTIVE_PROFILE         PFC_INV_PROFILE_36V
#define PFC_INV_PFC_5V_CALIBRATION_CONFIRMED  1U /* 已在独立PFC工程使用同一采样链完成5 V实测。 */
#define PFC_INV_PFC_36V_CALIBRATION_CONFIRMED 1U /* 已按当前独立PFC赛题档完成36 V带功率验证。 */
#define PFC_INV_INV_CALIBRATION_CONFIRMED 0U /* 只表示线电压工程量是否可信，不控制PWM。 */
#define PFC_INV_PWM_ENABLE             1U

/*
 * 1U沿用独立PFC的波形调试放宽策略：软件阈值和波形质量诊断只记录，不撤销PWM。
 * ADC/DMA失步、HAL错误、非有限数、Compare写入失败、FLT3和CPU/时钟异常仍然停机。
 * 没有独立OCP/DESAT时只能配合隔离、限流电源使用，不能把该开关当作硬件保护。
 */
#define PFC_INV_PFC_RELAXED_PWM_TEST   1U

/* 旧PFC接口只读取活动档确认位；该派生宏禁止用户手工填写。 */
#if (PFC_INV_ACTIVE_PROFILE == PFC_INV_PROFILE_5V)
#define PFC_INV_PFC_CALIBRATION_CONFIRMED PFC_INV_PFC_5V_CALIBRATION_CONFIRMED
#else
#define PFC_INV_PFC_CALIBRATION_CONFIRMED PFC_INV_PFC_36V_CALIBRATION_CONFIRMED
#endif

/* 联合层低速任务周期，修改后必须同步检查IWDG超时和串口占用。 */
#define PFC_INV_VOFA_PERIOD_MS         10U
#define PFC_INV_OLED_PERIOD_MS         100U
#define PFC_INV_SUPERVISOR_PERIOD_MS   100U
#define PFC_INV_VBUS_STABLE_MS         500U
#define PFC_INV_INV_SOFT_START_MS      1000U

/* ======================== PFC 5 V低压试验参数 ======================== */
#define PFC_INV_PFC_5V_VAC_NOMINAL_RMS       5.0f
#define PFC_INV_PFC_5V_GRID_FREQUENCY_HZ     50.0f
#define PFC_INV_PFC_5V_GRID_TOLERANCE_HZ     3.0f
#define PFC_INV_PFC_5V_VAC_PEAK_TRIP_V       8.5f
#define PFC_INV_PFC_5V_VBUS_TARGET_V         9.0f
#define PFC_INV_PFC_5V_VBUS_START_MIN_V      5.0f
#define PFC_INV_PFC_5V_VBUS_RUN_MIN_V        4.0f
#define PFC_INV_PFC_5V_VBUS_WARN_V           9.8f
#define PFC_INV_PFC_5V_VBUS_TRIP_V           10.5f
#define PFC_INV_PFC_5V_VBUS_TOLERANCE_V      0.5f
#define PFC_INV_PFC_5V_LOAD_RESISTANCE_OHM   30.0f
#define PFC_INV_PFC_5V_INPUT_INDUCTANCE_H    940.0e-6f
#define PFC_INV_PFC_5V_BUS_CAPACITANCE_F     4000.0e-6f
#define PFC_INV_PFC_5V_CONTROL_FREQUENCY_HZ  10000.0f
#define PFC_INV_PFC_5V_MODULATION_LIMIT      0.90f
#define PFC_INV_PFC_5V_CURRENT_TARGET_A_PEAK 0.80f
#define PFC_INV_PFC_5V_CURRENT_RAMP_A_PER_S  0.50f
#define PFC_INV_PFC_5V_CURRENT_TRIP_A_PEAK   1.20f
#define PFC_INV_PFC_5V_PR_KP                 0.50f
#define PFC_INV_PFC_5V_PR_KR                 5.0f
#define PFC_INV_PFC_5V_PR_BANDWIDTH_RAD_S    5.0f
#define PFC_INV_PFC_5V_PR_OUTPUT_LIMIT_V     3.0f
#define PFC_INV_PFC_5V_PI_KP_A_PER_V         0.05f
#define PFC_INV_PFC_5V_PI_KI_A_PER_VS        1.0f
#define PFC_INV_PFC_5V_VOLTAGE_LOOP_HZ       1000.0f
#define PFC_INV_PFC_5V_NOTCH_DAMPING_RAD_S   50.0f
#define PFC_INV_PFC_5V_VBUS_SLEW_V_PER_S     1.0f
#define PFC_INV_PFC_5V_PROBE_CURRENT_A_RMS   0.20f
#define PFC_INV_PFC_5V_PROBE_SLEW_A_PER_S    5.0f
#define PFC_INV_PFC_5V_CURRENT_ERROR_MAX_A_RMS 0.15f
#define PFC_INV_PFC_5V_PROBE_MIN_MS          60U
#define PFC_INV_PFC_5V_CURRENT_TIMEOUT_MS    500U
#define PFC_INV_PFC_5V_VBUS_TIMEOUT_MS       8000U
#define PFC_INV_PFC_5V_SATURATION_SAMPLES    200U

/*
 * 以下参数来自独立PFC工程在同一采样板、同一电阻/电位器和同一ADC接线下的5 V实测。
 * 首次迁移上板仍保持RAW_ADC和PWM=0，确认原始码未因供电、接地或连接器变化而漂移。
 */
#define PFC_INV_PFC_5V_IPFC_ZERO_COUNT      2046U
#define PFC_INV_PFC_5V_VAC_ZERO_COUNT       2046U
#define PFC_INV_PFC_5V_IPFC_A_PER_COUNT     0.003322f
#define PFC_INV_PFC_5V_VAC_V_PER_COUNT      0.02730f
#define PFC_INV_PFC_5V_VBUS_V_PER_COUNT     0.02106f
#define PFC_INV_PFC_5V_IPFC_POLARITY        1
#define PFC_INV_PFC_5V_VAC_POLARITY         1
#define PFC_INV_PFC_5V_BRIDGE_POLARITY      1

/* ======================== PFC 36 V赛题实测参数 ======================== */
#define PFC_INV_PFC_36V_VAC_NOMINAL_RMS       36.0f
#define PFC_INV_PFC_36V_GRID_FREQUENCY_HZ     50.0f
#define PFC_INV_PFC_36V_GRID_TOLERANCE_HZ     3.0f
#define PFC_INV_PFC_36V_VAC_PEAK_TRIP_V       53.5f
#define PFC_INV_PFC_36V_VBUS_TARGET_V         60.0f
#define PFC_INV_PFC_36V_VBUS_START_MIN_V      45.0f
#define PFC_INV_PFC_36V_VBUS_RUN_MIN_V        40.0f
#define PFC_INV_PFC_36V_VBUS_WARN_V           64.0f
#define PFC_INV_PFC_36V_VBUS_TRIP_V           66.0f
#define PFC_INV_PFC_36V_VBUS_TOLERANCE_V      1.0f
#define PFC_INV_PFC_36V_LOAD_RESISTANCE_OHM   30.0f
#define PFC_INV_PFC_36V_INPUT_INDUCTANCE_H    940.0e-6f
#define PFC_INV_PFC_36V_BUS_CAPACITANCE_F     4000.0e-6f
#define PFC_INV_PFC_36V_CONTROL_FREQUENCY_HZ  10000.0f
#define PFC_INV_PFC_36V_MODULATION_LIMIT      0.90f
#define PFC_INV_PFC_36V_CURRENT_TARGET_A_PEAK 5.80f
#define PFC_INV_PFC_36V_CURRENT_RAMP_A_PER_S  2.00f
#define PFC_INV_PFC_36V_CURRENT_TRIP_A_PEAK   6.20f
#define PFC_INV_PFC_36V_PR_KP                 1.00f /* V/A，加强瞬时电流误差校正，防止实际电流偏离参考后继续上升。 */
#define PFC_INV_PFC_36V_PR_KR                 8.00f /* V/A，加强50 Hz稳态跟踪，但仍保留10 V的PR输出限幅。 */
#define PFC_INV_PFC_36V_PR_BANDWIDTH_RAD_S    5.0f
#define PFC_INV_PFC_36V_PR_OUTPUT_LIMIT_V     10.0f
#define PFC_INV_PFC_36V_PI_KP_A_PER_V         0.05f /* A/V，降低INV投入后母线误差直接形成的电流阶跃。 */
#define PFC_INV_PFC_36V_PI_KI_A_PER_VS        0.20f /* A/(V*s)，避免母线暂时低于60 V时在数秒内把电流指令推满。 */
#define PFC_INV_PFC_36V_VOLTAGE_LOOP_HZ       1000.0f
#define PFC_INV_PFC_36V_NOTCH_DAMPING_RAD_S   50.0f
#define PFC_INV_PFC_36V_VBUS_SLEW_V_PER_S     5.0f
#define PFC_INV_PFC_36V_PROBE_CURRENT_A_RMS   0.80f /* A RMS，仅为PR启动探测值；PI外环随后仍可升至约4.10 A RMS。 */
#define PFC_INV_PFC_36V_PROBE_SLEW_A_PER_S    8.0f  /* A RMS/s，约100 ms升到0.8 A，减小单半周启动浪涌。 */
#define PFC_INV_PFC_36V_CURRENT_ERROR_MAX_A_RMS 0.35f
#define PFC_INV_PFC_36V_PROBE_MIN_MS          100U  /* 至少观察5个50 Hz周期后再切入母线PI。 */
#define PFC_INV_PFC_36V_CURRENT_TIMEOUT_MS    800U
#define PFC_INV_PFC_36V_VBUS_TIMEOUT_MS       8000U
#define PFC_INV_PFC_36V_SATURATION_SAMPLES    200U
/*
 * 以下零点、比例和极性与当前独立PFC赛题档保持一致。若更换采样板、运放电阻、
 * 连接器或ADC引脚，必须退回RAW_ADC重新标定，不能继续沿用确认位1U。
 */
#define PFC_INV_PFC_36V_IPFC_ZERO_COUNT       2046U
#define PFC_INV_PFC_36V_VAC_ZERO_COUNT        2046U
#define PFC_INV_PFC_36V_IPFC_A_PER_COUNT      0.003323f
#define PFC_INV_PFC_36V_VAC_V_PER_COUNT       0.02730f
#define PFC_INV_PFC_36V_VBUS_V_PER_COUNT      0.021062f
#define PFC_INV_PFC_36V_IPFC_POLARITY         1
#define PFC_INV_PFC_36V_VAC_POLARITY          1
#define PFC_INV_PFC_36V_BRIDGE_POLARITY       1

/* ======================== INV采样与开环参数 ======================== */
#define PFC_INV_INV_OUTPUT_FREQUENCY       60U /* 只允许30U或60U，修改后必须重新核对采样和负载。 */
#define PFC_INV_INV_LINE_RMS_V_5V          2.5f
#define PFC_INV_INV_LINE_RMS_V_36V         32.0f
#define PFC_INV_INV_CURRENT_PRIORITY_MODE  1U  /* 联合测试优先提高线电流，不等待PFC母线闭环。 */
#define PFC_INV_INV_CURRENT_PRIORITY_LINE_RMS_V_5V  2.5f
#define PFC_INV_INV_CURRENT_PRIORITY_LINE_RMS_V_36V 33.0f /* 60 V母线下约0.90调制度。 */
#define PFC_INV_INV_FIXED_DC_BUS_V          60.0f /* V，INV开环固定母线；实际母线偏差会同比影响输出线电压。 */
#define PFC_INV_INV_SOFT_START_MS          1000U
#define PFC_INV_INV_MODULATION_LIMIT       0.90f
#define PFC_INV_INV_MINIMUM_DC_V           2.0f
#define PFC_INV_INV_CONTROL_FREQUENCY_HZ   10000U
#define PFC_INV_INV_OFFSET_SAMPLES         256U
#define PFC_INV_INV_GAIN_SAMPLES           256U
#define PFC_INV_INV_CAL_MIN_DELTA_COUNTS   32U
#define PFC_INV_INV_CALIBRATION_CHANNEL    0U
#define PFC_INV_INV_CALIBRATION_REFERENCE  1.0f
#define PFC_INV_INV_ADC_MAX_SKEW_FRAMES    2U
#define PFC_INV_INV_ADC_RAIL_LOW_COUNT     16U
#define PFC_INV_INV_ADC_RAIL_HIGH_COUNT    4079U
#define PFC_INV_INV_ADC_RAIL_CONFIRM_FRAMES 8U

/*
 * 六路默认中点/比例仅用于接口完整性；实际值必须由每块采样板实测后替换。
 * OFFSET单位为ADC count；SCALE单位依次为A/count或V/count，必须始终填写正数。
 * POLARITY只能写+1或-1：已知的正向电流/线电压换算结果为负时改成-1，不能把负号
 * 藏进SCALE、更不能在CBSVPWM或PFC/INV控制器中另加反号。改变任一字段后必须保持
 * PWM=0重新检查工程量，随后才允许把对应CALIBRATION_CONFIRMED置1。
 */
#define PFC_INV_INV_IU_OFFSET 2048U
#define PFC_INV_INV_IV_OFFSET 2048U
#define PFC_INV_INV_IW_OFFSET 2048U
#define PFC_INV_INV_VUV_OFFSET 2048U
#define PFC_INV_INV_VVW_OFFSET 2048U
#define PFC_INV_INV_VWU_OFFSET 2048U
#define PFC_INV_INV_IU_SCALE  0.001f
#define PFC_INV_INV_IV_SCALE  0.001f
#define PFC_INV_INV_IW_SCALE  0.001f
#define PFC_INV_INV_VUV_SCALE 0.010f
#define PFC_INV_INV_VVW_SCALE 0.010f
#define PFC_INV_INV_VWU_SCALE 0.010f
#define PFC_INV_INV_IU_POLARITY  1
#define PFC_INV_INV_IV_POLARITY  1
#define PFC_INV_INV_IW_POLARITY  1
#define PFC_INV_INV_VUV_POLARITY 1
#define PFC_INV_INV_VVW_POLARITY 1
#define PFC_INV_INV_VWU_POLARITY 1

/* ======================== 兼容宏：PFC旧模块使用 ======================== */
#define PFC_USER_PROFILE_5V  PFC_INV_PROFILE_5V
#define PFC_USER_PROFILE_36V PFC_INV_PROFILE_36V
#define PFC_USER_PROFILE_CONTEST_36V PFC_INV_PROFILE_36V
#if (PFC_INV_STAGE == PFC_INV_STAGE_RAW_ADC)
#define PFC_USER_RUN_MODE PFC_USER_MODE_RAW_ADC
#elif (PFC_INV_STAGE == PFC_INV_STAGE_INV_ONLY)
#define PFC_USER_RUN_MODE PFC_USER_MODE_ENGINEERING_CHECK
#else
#define PFC_USER_RUN_MODE PFC_USER_MODE_CLOSED_LOOP
#endif
#define PFC_USER_ACTIVE_PROFILE PFC_INV_ACTIVE_PROFILE
#define PFC_USER_RELAXED_PWM_TEST PFC_INV_PFC_RELAXED_PWM_TEST
#define PFC_USER_5V_CALIBRATION_CONFIRMED PFC_INV_PFC_5V_CALIBRATION_CONFIRMED
#define PFC_USER_36V_CALIBRATION_CONFIRMED PFC_INV_PFC_36V_CALIBRATION_CONFIRMED

#define PFC_USER_5V_VAC_NOMINAL_RMS PFC_INV_PFC_5V_VAC_NOMINAL_RMS
#define PFC_USER_5V_GRID_FREQUENCY_HZ PFC_INV_PFC_5V_GRID_FREQUENCY_HZ
#define PFC_USER_5V_GRID_TOLERANCE_HZ PFC_INV_PFC_5V_GRID_TOLERANCE_HZ
#define PFC_USER_5V_VAC_PEAK_TRIP_V PFC_INV_PFC_5V_VAC_PEAK_TRIP_V
#define PFC_USER_5V_VBUS_TARGET_V PFC_INV_PFC_5V_VBUS_TARGET_V
#define PFC_USER_5V_VBUS_START_MIN_V PFC_INV_PFC_5V_VBUS_START_MIN_V
#define PFC_USER_5V_VBUS_RUN_MIN_V PFC_INV_PFC_5V_VBUS_RUN_MIN_V
#define PFC_USER_5V_VBUS_WARN_V PFC_INV_PFC_5V_VBUS_WARN_V
#define PFC_USER_5V_VBUS_TRIP_V PFC_INV_PFC_5V_VBUS_TRIP_V
#define PFC_USER_5V_VBUS_TOLERANCE_V PFC_INV_PFC_5V_VBUS_TOLERANCE_V
#define PFC_USER_5V_LOAD_RESISTANCE_OHM PFC_INV_PFC_5V_LOAD_RESISTANCE_OHM
#define PFC_USER_5V_INPUT_INDUCTANCE_H PFC_INV_PFC_5V_INPUT_INDUCTANCE_H
#define PFC_USER_5V_BUS_CAPACITANCE_F PFC_INV_PFC_5V_BUS_CAPACITANCE_F
#define PFC_USER_5V_CONTROL_FREQUENCY_HZ PFC_INV_PFC_5V_CONTROL_FREQUENCY_HZ
#define PFC_USER_5V_MODULATION_LIMIT PFC_INV_PFC_5V_MODULATION_LIMIT
#define PFC_USER_5V_CURRENT_TARGET_A_PEAK PFC_INV_PFC_5V_CURRENT_TARGET_A_PEAK
#define PFC_USER_5V_CURRENT_RAMP_A_PER_S PFC_INV_PFC_5V_CURRENT_RAMP_A_PER_S
#define PFC_USER_5V_CURRENT_TRIP_A_PEAK PFC_INV_PFC_5V_CURRENT_TRIP_A_PEAK
#define PFC_USER_5V_PR_KP PFC_INV_PFC_5V_PR_KP
#define PFC_USER_5V_PR_KR PFC_INV_PFC_5V_PR_KR
#define PFC_USER_5V_PR_BANDWIDTH_RAD_S PFC_INV_PFC_5V_PR_BANDWIDTH_RAD_S
#define PFC_USER_5V_PR_OUTPUT_LIMIT_V PFC_INV_PFC_5V_PR_OUTPUT_LIMIT_V
#define PFC_USER_5V_PI_KP_A_PER_V PFC_INV_PFC_5V_PI_KP_A_PER_V
#define PFC_USER_5V_PI_KI_A_PER_VS PFC_INV_PFC_5V_PI_KI_A_PER_VS
#define PFC_USER_5V_VOLTAGE_LOOP_HZ PFC_INV_PFC_5V_VOLTAGE_LOOP_HZ
#define PFC_USER_5V_NOTCH_DAMPING_RAD_S PFC_INV_PFC_5V_NOTCH_DAMPING_RAD_S
#define PFC_USER_5V_VBUS_SLEW_V_PER_S PFC_INV_PFC_5V_VBUS_SLEW_V_PER_S
#define PFC_USER_5V_PROBE_CURRENT_A_RMS PFC_INV_PFC_5V_PROBE_CURRENT_A_RMS
#define PFC_USER_5V_PROBE_SLEW_A_PER_S PFC_INV_PFC_5V_PROBE_SLEW_A_PER_S
#define PFC_USER_5V_CURRENT_ERROR_MAX_A_RMS PFC_INV_PFC_5V_CURRENT_ERROR_MAX_A_RMS
#define PFC_USER_5V_PROBE_MIN_MS PFC_INV_PFC_5V_PROBE_MIN_MS
#define PFC_USER_5V_CURRENT_TIMEOUT_MS PFC_INV_PFC_5V_CURRENT_TIMEOUT_MS
#define PFC_USER_5V_VBUS_TIMEOUT_MS PFC_INV_PFC_5V_VBUS_TIMEOUT_MS
#define PFC_USER_5V_SATURATION_SAMPLES PFC_INV_PFC_5V_SATURATION_SAMPLES
#define PFC_USER_5V_IPFC_ZERO_COUNT PFC_INV_PFC_5V_IPFC_ZERO_COUNT
#define PFC_USER_5V_VAC_ZERO_COUNT PFC_INV_PFC_5V_VAC_ZERO_COUNT
#define PFC_USER_5V_IPFC_A_PER_COUNT PFC_INV_PFC_5V_IPFC_A_PER_COUNT
#define PFC_USER_5V_VAC_V_PER_COUNT PFC_INV_PFC_5V_VAC_V_PER_COUNT
#define PFC_USER_5V_VBUS_V_PER_COUNT PFC_INV_PFC_5V_VBUS_V_PER_COUNT
#define PFC_USER_5V_IPFC_POLARITY PFC_INV_PFC_5V_IPFC_POLARITY
#define PFC_USER_5V_VAC_POLARITY PFC_INV_PFC_5V_VAC_POLARITY
#define PFC_USER_5V_BRIDGE_POLARITY PFC_INV_PFC_5V_BRIDGE_POLARITY

#define PFC_USER_36V_VAC_NOMINAL_RMS PFC_INV_PFC_36V_VAC_NOMINAL_RMS
#define PFC_USER_36V_GRID_FREQUENCY_HZ PFC_INV_PFC_36V_GRID_FREQUENCY_HZ
#define PFC_USER_36V_GRID_TOLERANCE_HZ PFC_INV_PFC_36V_GRID_TOLERANCE_HZ
#define PFC_USER_36V_VAC_PEAK_TRIP_V PFC_INV_PFC_36V_VAC_PEAK_TRIP_V
#define PFC_USER_36V_VBUS_TARGET_V PFC_INV_PFC_36V_VBUS_TARGET_V
#define PFC_USER_36V_VBUS_START_MIN_V PFC_INV_PFC_36V_VBUS_START_MIN_V
#define PFC_USER_36V_VBUS_RUN_MIN_V PFC_INV_PFC_36V_VBUS_RUN_MIN_V
#define PFC_USER_36V_VBUS_WARN_V PFC_INV_PFC_36V_VBUS_WARN_V
#define PFC_USER_36V_VBUS_TRIP_V PFC_INV_PFC_36V_VBUS_TRIP_V
#define PFC_USER_36V_VBUS_TOLERANCE_V PFC_INV_PFC_36V_VBUS_TOLERANCE_V
#define PFC_USER_36V_LOAD_RESISTANCE_OHM PFC_INV_PFC_36V_LOAD_RESISTANCE_OHM
#define PFC_USER_36V_INPUT_INDUCTANCE_H PFC_INV_PFC_36V_INPUT_INDUCTANCE_H
#define PFC_USER_36V_BUS_CAPACITANCE_F PFC_INV_PFC_36V_BUS_CAPACITANCE_F
#define PFC_USER_36V_CONTROL_FREQUENCY_HZ PFC_INV_PFC_36V_CONTROL_FREQUENCY_HZ
#define PFC_USER_36V_MODULATION_LIMIT PFC_INV_PFC_36V_MODULATION_LIMIT
#define PFC_USER_36V_CURRENT_TARGET_A_PEAK PFC_INV_PFC_36V_CURRENT_TARGET_A_PEAK
#define PFC_USER_36V_CURRENT_RAMP_A_PER_S PFC_INV_PFC_36V_CURRENT_RAMP_A_PER_S
#define PFC_USER_36V_CURRENT_TRIP_A_PEAK PFC_INV_PFC_36V_CURRENT_TRIP_A_PEAK
#define PFC_USER_36V_PR_KP PFC_INV_PFC_36V_PR_KP
#define PFC_USER_36V_PR_KR PFC_INV_PFC_36V_PR_KR
#define PFC_USER_36V_PR_BANDWIDTH_RAD_S PFC_INV_PFC_36V_PR_BANDWIDTH_RAD_S
#define PFC_USER_36V_PR_OUTPUT_LIMIT_V PFC_INV_PFC_36V_PR_OUTPUT_LIMIT_V
#define PFC_USER_36V_PI_KP_A_PER_V PFC_INV_PFC_36V_PI_KP_A_PER_V
#define PFC_USER_36V_PI_KI_A_PER_VS PFC_INV_PFC_36V_PI_KI_A_PER_VS
#define PFC_USER_36V_VOLTAGE_LOOP_HZ PFC_INV_PFC_36V_VOLTAGE_LOOP_HZ
#define PFC_USER_36V_NOTCH_DAMPING_RAD_S PFC_INV_PFC_36V_NOTCH_DAMPING_RAD_S
#define PFC_USER_36V_VBUS_SLEW_V_PER_S PFC_INV_PFC_36V_VBUS_SLEW_V_PER_S
#define PFC_USER_36V_PROBE_CURRENT_A_RMS PFC_INV_PFC_36V_PROBE_CURRENT_A_RMS
#define PFC_USER_36V_PROBE_SLEW_A_PER_S PFC_INV_PFC_36V_PROBE_SLEW_A_PER_S
#define PFC_USER_36V_CURRENT_ERROR_MAX_A_RMS PFC_INV_PFC_36V_CURRENT_ERROR_MAX_A_RMS
#define PFC_USER_36V_PROBE_MIN_MS PFC_INV_PFC_36V_PROBE_MIN_MS
#define PFC_USER_36V_CURRENT_TIMEOUT_MS PFC_INV_PFC_36V_CURRENT_TIMEOUT_MS
#define PFC_USER_36V_VBUS_TIMEOUT_MS PFC_INV_PFC_36V_VBUS_TIMEOUT_MS
#define PFC_USER_36V_SATURATION_SAMPLES PFC_INV_PFC_36V_SATURATION_SAMPLES
#define PFC_USER_36V_IPFC_ZERO_COUNT PFC_INV_PFC_36V_IPFC_ZERO_COUNT
#define PFC_USER_36V_VAC_ZERO_COUNT PFC_INV_PFC_36V_VAC_ZERO_COUNT
#define PFC_USER_36V_IPFC_A_PER_COUNT PFC_INV_PFC_36V_IPFC_A_PER_COUNT
#define PFC_USER_36V_VAC_V_PER_COUNT PFC_INV_PFC_36V_VAC_V_PER_COUNT
#define PFC_USER_36V_VBUS_V_PER_COUNT PFC_INV_PFC_36V_VBUS_V_PER_COUNT
#define PFC_USER_36V_IPFC_POLARITY PFC_INV_PFC_36V_IPFC_POLARITY
#define PFC_USER_36V_VAC_POLARITY PFC_INV_PFC_36V_VAC_POLARITY
#define PFC_USER_36V_BRIDGE_POLARITY PFC_INV_PFC_36V_BRIDGE_POLARITY

/* ======================== 兼容宏：INV旧模块使用 ======================== */
#define INV_MODE_ADC_CALIBRATION 0U
#define INV_MODE_PWM_WAVEFORM    1U
#define INV_MODE_OPEN_LOOP       2U
#define INV_CAL_STEP_ZERO        0U
#define INV_CAL_STEP_GAIN        1U
#if (PFC_INV_STAGE == PFC_INV_STAGE_RAW_ADC)
#define INV_USER_WORK_MODE INV_MODE_ADC_CALIBRATION
#else
#define INV_USER_WORK_MODE INV_MODE_PWM_WAVEFORM
#endif
#define INV_USER_ENABLE_PWM_OUTPUT PFC_INV_PWM_ENABLE
#define INV_USER_RELAXED_MONITORING PFC_INV_PFC_RELAXED_PWM_TEST
#define INV_USER_OUTPUT_FREQUENCY PFC_INV_INV_OUTPUT_FREQUENCY
#define INV_USER_DC_BUS_V PFC_INV_INV_FIXED_DC_BUS_V
#if (PFC_INV_ACTIVE_PROFILE == PFC_INV_PROFILE_36V)
#define INV_USER_LINE_RMS_V PFC_INV_INV_LINE_RMS_V_36V
#else
#define INV_USER_LINE_RMS_V PFC_INV_INV_LINE_RMS_V_5V
#endif
#define INV_USER_SOFT_START_MS PFC_INV_INV_SOFT_START_MS
#define INV_USER_MODULATION_LIMIT PFC_INV_INV_MODULATION_LIMIT
#define INV_USER_CONTROL_FREQUENCY_HZ PFC_INV_INV_CONTROL_FREQUENCY_HZ
#define INV_USER_MINIMUM_DC_V PFC_INV_INV_MINIMUM_DC_V
#define INV_USER_OFFSET_SAMPLES PFC_INV_INV_OFFSET_SAMPLES
#define INV_USER_GAIN_SAMPLES PFC_INV_INV_GAIN_SAMPLES
#define INV_USER_CAL_MIN_DELTA_COUNTS PFC_INV_INV_CAL_MIN_DELTA_COUNTS
#define INV_USER_CALIBRATION_STEP INV_CAL_STEP_ZERO
#define INV_USER_CALIBRATION_CHANNEL PFC_INV_INV_CALIBRATION_CHANNEL
#define INV_USER_CALIBRATION_REFERENCE PFC_INV_INV_CALIBRATION_REFERENCE
#define INV_USER_ADC_MAX_SKEW_FRAMES PFC_INV_INV_ADC_MAX_SKEW_FRAMES
#define INV_USER_ADC_RAIL_LOW_COUNT PFC_INV_INV_ADC_RAIL_LOW_COUNT
#define INV_USER_ADC_RAIL_HIGH_COUNT PFC_INV_INV_ADC_RAIL_HIGH_COUNT
#define INV_USER_ADC_RAIL_CONFIRM_FRAMES PFC_INV_INV_ADC_RAIL_CONFIRM_FRAMES
#define INV_USER_IU_OFFSET PFC_INV_INV_IU_OFFSET
#define INV_USER_IV_OFFSET PFC_INV_INV_IV_OFFSET
#define INV_USER_IW_OFFSET PFC_INV_INV_IW_OFFSET
#define INV_USER_VUV_OFFSET PFC_INV_INV_VUV_OFFSET
#define INV_USER_VVW_OFFSET PFC_INV_INV_VVW_OFFSET
#define INV_USER_VWU_OFFSET PFC_INV_INV_VWU_OFFSET
#define INV_USER_IU_SCALE_A_PER_COUNT PFC_INV_INV_IU_SCALE
#define INV_USER_IV_SCALE_A_PER_COUNT PFC_INV_INV_IV_SCALE
#define INV_USER_IW_SCALE_A_PER_COUNT PFC_INV_INV_IW_SCALE
#define INV_USER_VUV_SCALE_V_PER_COUNT PFC_INV_INV_VUV_SCALE
#define INV_USER_VVW_SCALE_V_PER_COUNT PFC_INV_INV_VVW_SCALE
#define INV_USER_VWU_SCALE_V_PER_COUNT PFC_INV_INV_VWU_SCALE
#define INV_USER_LIMITED_MAX_FRAMES 200U
#define INV_USER_STARTUP_TIMEOUT_MS 2000U
#define INV_USER_VOFA_PERIOD_MS PFC_INV_VOFA_PERIOD_MS
#define INV_USER_OLED_PERIOD_MS PFC_INV_OLED_PERIOD_MS
#define INV_USER_SUPERVISOR_PERIOD_MS PFC_INV_SUPERVISOR_PERIOD_MS

/* 12位ADC和极性是最容易被误填的字段，尽早让编译器拦截明显错误。 */
#if (PFC_INV_ACTIVE_PROFILE != PFC_INV_PROFILE_5V) && (PFC_INV_ACTIVE_PROFILE != PFC_INV_PROFILE_36V)
#error "PFC_INV_ACTIVE_PROFILE must be 5V or 36V"
#endif
#if (PFC_INV_STAGE > PFC_INV_STAGE_JOINT_CONTEST)
#error "PFC_INV_STAGE is invalid"
#endif
#if (PFC_INV_PWM_ENABLE != 0U) && (PFC_INV_PWM_ENABLE != 1U)
#error "PFC_INV_PWM_ENABLE must be 0U or 1U"
#endif
#if (PFC_INV_PFC_RELAXED_PWM_TEST != 0U) && (PFC_INV_PFC_RELAXED_PWM_TEST != 1U)
#error "PFC_INV_PFC_RELAXED_PWM_TEST must be 0U or 1U"
#endif
#if (PFC_INV_INV_CURRENT_PRIORITY_MODE != 0U) && (PFC_INV_INV_CURRENT_PRIORITY_MODE != 1U)
#error "PFC_INV_INV_CURRENT_PRIORITY_MODE must be 0U or 1U"
#endif
#if (PFC_INV_PFC_5V_CALIBRATION_CONFIRMED != 0U) && (PFC_INV_PFC_5V_CALIBRATION_CONFIRMED != 1U)
#error "PFC 5V calibration confirmation must be 0U or 1U"
#endif
#if (PFC_INV_PFC_36V_CALIBRATION_CONFIRMED != 0U) && (PFC_INV_PFC_36V_CALIBRATION_CONFIRMED != 1U)
#error "PFC 36V calibration confirmation must be 0U or 1U"
#endif
#if (PFC_INV_INV_CALIBRATION_CONFIRMED != 0U) && (PFC_INV_INV_CALIBRATION_CONFIRMED != 1U)
#error "INV calibration confirmation must be 0U or 1U"
#endif
#if (PFC_INV_PWM_ENABLE == 1U) && (PFC_INV_STAGE == PFC_INV_STAGE_PFC_ONLY) && (PFC_INV_PFC_CALIBRATION_CONFIRMED != 1U)
#error "PFC-only PWM output requires confirmed PFC ADC calibration"
#endif

#endif /* PFC_INV_USER_CONFIG_H */
