# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/fpga/AM_Decoder/AM_Decoder.cache/wt [current_project]
set_property parent.project_path D:/fpga/AM_Decoder/AM_Decoder.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/fpga/AM_Decoder/AM_Decoder.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/fpga/fm_3.25_0.06.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample1m_Fstop0.21m_Fpass0.2m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_Fstop6m_Fpass5m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_Fstop8m_Fpass5m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_fpass1m_fstop3m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_fpass5m_fstop6.5m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_Fpass1m_Fstop3.8m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_Fstop8m_Fpass1m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample1m_Fpass30k_Fstop35k.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample130m_Fpass0.5m_Fstop4m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample5m_Fstop70k_Fpass35k.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample43m_Fpass0.5m_Fstop1m.coe
add_files c:/Users/admin/Desktop/fir.coe/Sample60k_Fpass11.5k_Fstop12k.coe
read_verilog -library xil_defaultlib {
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/AD9226.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/ASK_decode.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/DDS_2.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/FIR_ASK.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/IQ_FreMix_Low.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/detect_ASK.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/hdl/system_wrapper.v
  D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/new/main.v
}
read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/cordic_0/cordic_0.xci

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_1/mult_gen_1.xci

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci

add_files D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/bd/system/system_ooc.xdc]

read_ip -quiet D:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc]

read_ip -quiet d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1.xci
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/dds_compiler_1/dds_compiler_1_ooc.xdc]

read_ip -quiet d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_2/fir_compiler_2.xci
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_2/constraints/fir_compiler_v7_2.xdc]
set_property used_in_implementation false [get_files -all d:/fpga/AM_Decoder/AM_Decoder.srcs/sources_1/ip/fir_compiler_2/fir_compiler_2_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/fpga/AM_Decoder/AM_Decoder.srcs/constrs_1/new/Version1.xdc
set_property used_in_implementation false [get_files D:/fpga/AM_Decoder/AM_Decoder.srcs/constrs_1/new/Version1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top main -part xc7z020clg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef main.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
